services:
  # __________________________________________________________________________________________________
  # ---- CONTENEDORES DE MONGO CON REPLICA SET----
  docsflowdatabase1:
    image: mongo:7.0
    container_name: docsflowdatabase1
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo-keyfile
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile
      - ./docsflowdatabase1:/data/db
    ports:
      - "27017:27017"

  docsflowdatabase2:
    image: mongo:7.0
    container_name: docsflowdatabase2
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo-keyfile
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile
      - ./docsflowdatabase2:/data/db
    ports:
      - "27018:27017"

  docsflowdatabase3:
    image: mongo:7.0
    container_name: docsflowdatabase3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo-keyfile
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile
      - ./docsflowdatabase3:/data/db
    ports:
      - "27019:27017"

  # __________________________________________________________________________________________________
  # ---- CONTENEDORES DE MICROSERVICIOS Y REPLICAS----

  # ---- MICROSERVICIO 1 Y SU REPLICA ---
  auth_service: &auth_service_base
    image: node:22
    container_name: auth_service
    working_dir: /app
    depends_on:
      - docsflowdatabase1
      - docsflowdatabase2
      - docsflowdatabase3
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      MONGO_URI: ${MONGO_URI}
    volumes:
      - ./auth_service:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"

  auth_service_replica:
    <<: *auth_service_base
    container_name: auth_service_replica
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      MONGO_URI: ${MONGO_URI}
      IS_REPLICA: "true"
    ports:
      - "3001:3000"

  # ---- MICROSERVICIO 2: USER SERVICE Y SU REPLICA----
  user_service: &user_service_base
    image: node:22
    container_name: user_service
    working_dir: /app
    depends_on:
      - docsflowdatabase1
    environment:
      MONGO_URI: ${MONGO_URI}
    volumes:
      - ./user_service:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3002:3000"

  user_service_replica:
    <<: *auth_service_base
    container_name: user_service_replica
    environment:
      MONGO_URI: ${MONGO_URI}
      IS_REPLICA: "true"
    ports:
      - "3003:3000"

  # __________________________________________________________________________________________________
  # ---- CONTENEDOR DE NGINX, PROXY REVERSE ----
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth_service
      - auth_service_replica
      - user_service
      - user_service_replica
    