events{}

# Controlar Proxy-Reversee
http{
    # Establecer servicios
    upstream Auth_Service{
        server auth_service:3000;
        server auth_service_replica:3000;
    }
    
    server{
        listen 80;

        # Rutas donde van a mandar las peticiones
        location /auth/{
            proxy_pass http://Auth_Service/;
            proxy_set_header HOST $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
