events{}

# Controlar Proxy-Reversee
http{
    # Establecer servicios
    upstream Auth_Service{
        server auth_service:3000;
        server auth_service_replica:3000;
    }

    upstream User_Service{
        server user_service:3000;
        server user_service_replica:3000;
    }

    upstream Doc_Service{
        server docs_service:3000;
        server docs_service_replica:3000;
    }
    
    server{
        listen 80;

        # Rutas donde van a mandar las peticiones
        location /auth/{
            proxy_pass http://Auth_Service/;
            proxy_set_header HOST $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /user/{
            proxy_pass http://User_Service/;
            proxy_set_header HOST $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /documents/ {
            proxy_pass http://Doc_Service/;
            proxy_set_header HOST $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_read_timeout 600s;
            proxy_connect_timeout 600s;
            proxy_send_timeout 600s;
        }
    }
}
